[project]
name = "tcg-matchmaker"
major_version = 15

[auth]
enabled = true

[auth.email]
enable_confirmations = false

[api]
enabled = true

[db]
enabled_extensions = ["postgis"]

[analytics]
enabled = false

[storage]
enabled = true

[storage.buckets]
avatars = { public = false, file_size_limit = "2MB", allowed_mime_types = ["image/jpeg"] }
logos = { public = true, file_size_limit = "2MB", allowed_mime_types = ["image/jpeg"] }

[auth.external]
enabled = false
