export default {
  app: { title: 'TCG Matchmaker', subtitle: 'Encontre partidas perto de você' },
  nav: { home: 'Início', matches: 'Partidas', trading: 'Negociações', tournaments: 'Torneios', stores: 'Lojas', login: 'Entrar', signup: 'Cadastrar', logout: 'Sair', settings: 'Configurações', admin: 'Admin', newMatch: 'Nova Partida', newTrading: 'Nova Sessão', newTournament: 'Novo Torneio', newStore: 'Adicionar Loja' },
  auth: { email: 'Email', password: 'Senha', username: 'Usuário', displayName: 'Nome de Exibição', signIn: 'Entrar', signUp: 'Cadastrar', signOut: 'Sair', noAccount: 'Não tem conta?', haveAccount: 'Já tem conta?', onboarding: 'Bem-vindo! Crie a primeira conta de administrador', createAdmin: 'Criar Admin' },
  common: { loading: 'Carregando...', error: 'Erro', success: 'Sucesso', cancel: 'Cancelar', save: 'Salvar', delete: 'Excluir', confirm: 'Confirmar', search: 'Buscar', noResults: 'Nenhum resultado encontrado', back: 'Voltar', language: 'Idioma', darkMode: 'Modo Escuro' },
  home: { map: 'Mapa', list: 'Lista', findNearMe: 'Encontrar perto de mim', recentEvents: 'Eventos Recentes', noEvents: 'Nenhum evento por perto', heading: 'Partidas e Eventos Próximos' },
  store: { create: 'Adicionar Loja', name: 'Nome da Loja', address: 'Endereço', phone: 'Telefone', website: 'Site', members: 'Membros', owner: 'Dono', manager: 'Gerente', staff: 'Funcionário', verified: 'Verificada', settings: 'Config. da Loja', city: 'Cidade', state: 'Estado', latitude: 'Latitude', longitude: 'Longitude', details: 'Detalhes da Loja', noMembers: 'Sem membros' },
  event: { create: 'Criar Evento', type: 'Tipo', match: 'Partida', trading: 'Sessão de Negociação', tournament: 'Torneio', date: 'Data', time: 'Horário', location: 'Local', participants: 'Participantes', join: 'Participar', leave: 'Sair', confirm: 'Confirmar Presença', cancel: 'Cancelar Evento', status: 'Status', open: 'Aberto', confirmed: 'Confirmado', completed: 'Concluído', cancelled: 'Cancelado', details: 'Detalhes', players: 'Jogadores', all: 'Todos', createMatch: 'Criar Partida', createTrading: 'Criar Sessão', createTournament: 'Criar Torneio', matchDetails: 'Detalhes da Partida', tradingDetails: 'Detalhes da Sessão', rsvp: 'Confirmar', scheduledAt: 'Data e Hora', maxParticipants: 'Máx. Participantes', anyTcg: 'Qualquer TCG', attendee: 'Participante' },
  admin: { dashboard: 'Painel', manageTcgs: 'Gerenciar TCGs', manageUsers: 'Gerenciar Usuários', manageStores: 'Gerenciar Lojas', reports: 'Denúncias', auditLog: 'Registro de Auditoria', newTcg: 'Novo TCG', newFormat: 'Novo Formato', ban: 'Banir', unban: 'Desbanir', promote: 'Promover', resolve: 'Resolver', dismiss: 'Rejeitar' },
  match: { statusFilter: 'Filtro de Status', byDate: 'Por Data', playerCount: 'Nº de Jogadores' },
  profile: { title: 'Perfil', memberSince: 'Membro desde', eventHistory: 'Histórico de Eventos', noEvents: 'Nenhum evento ainda', role: 'Função' },
  tournament: { publish: 'Publicar', start: 'Iniciar', register: 'Inscrever', checkIn: 'Check-in', bracket: 'Chaveamento', manage: 'Gerenciar', walkover: 'W.O.', report: 'Reportar Resultado' },
};
